name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag test
        docker run --name test test
    - name: Copy container build output
      run:
        docker cp test:/test.txt .
    - name: Publish Test
      uses: actions/upload-artifact@v3
      with:
        name: Test
        path: ${{github.workspace}}/test.txt
