name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |
        docker build --target build -t hlbuildimage -f Dockerfile .
        docker run --name hlbuildcontainer hlbuildimage
    - name: Copy container build output
      run:
        docker cp hlbuildcontainer:/test.txt .
    - name: Publish Test
      uses: actions/upload-artifact@v3
      with:
        name: Test
        path: ${{github.workspace}}/test.txt
